apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: wb-test-2
spec:
  ports:
    - port: 8082
      targetPort: 80
  selector:
    app: web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: wb-test-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: api
          image: psdockerrun/web
          env:
            - name: Environment
              value: TEST
            - name: Debug__ShowHost
              value: "true"
          volumeMounts:
            - name: logging-config
              mountPath: "/app/config"
              readOnly: true
            - name: api-config
              mountPath: "/app/secrets"
              readOnly: true
      volumes:
        - name: logging-config
          configMap:
            name: web-logging
        - name: api-config
          secret:
            secretName: web-api
