apiVersion: v1
kind: Secret
metadata:
  name: products-api-db
  namespace: wb-test-2
type: Opaque
stringData:
  application.properties: |-
    spring.jpa.database=POSTGRESQL
    spring.datasource.platform=postgres
    spring.datasource.url=jdbc:postgresql://products-db:5432/postgres
    spring.datasource.username=postgres
    spring.datasource.password=wiredtestm3
