apiVersion: v1
kind: Secret
metadata:
  name: stock-api-connection
  namespace: wb-test-2
type: Opaque
stringData:
  POSTGRES_CONNECTION_STRING: "host=products-db port=5432 user=postgres password=wiredtestm3 dbname=postgres sslmode=disable"
