apiVersion: v1
kind: Secret
metadata:
  name: web-api
  namespace: wb-test-2
type: Opaque
stringData:
  api.json: |-
    {
      "ProductsApi": {
        "Url": "http://products-api/products"
      },
      "StockApi": {
        "Url": "http://stock-api:8080/stock"
      }
    }
