apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
spec:
  selector:
    matchLabels:
      app: products-db
  template:
    metadata:
      labels:
        app: products-db
    spec:
      containers:
        - name: api
          image: psdockerrun/products-db
          env:
            - name: POSTGRES_PASSWORD
              value: wired
