apiVersion: v1
kind: Service
metadata:
  name: products-api
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: products-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
spec:
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
        - name: api
          image: psdockerrun/products-api
