apiVersion: v1
kind: Service
metadata:
  name: stock-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: stock-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
spec:
  selector:
    matchLabels:
      app: stock-api
  template:
    metadata:
      labels:
        app: stock-api
    spec:
      containers:
        - name: api
          image: psdockerrun/stock-api
